name: Deploy

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: ["main", "dev"]
    types: 
      - completed

env:
  DOCKER_IMAGE: tmkrtchyan/app
  DOCKER_TAG: latest
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT: myapp1-deployment
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: devops-dev-eksdemo1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $AWS_REGION
          cluster_name: $EKS_CLUSTER_NAME
        with:
          args: |
            kubectl set image deployment $K8S_DEPLOYMENT -n $K8S_NAMESPACE
            $K8S_DEPLOYMENT=$DOCKER_IMAGE:$DOCKER_TAG &&
            kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE
