name: Docker Image CI

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./srcs
      run: |
        docker-compose build
        docker-compose up --tag my-image-name:$(date +%s)
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        repository: tmkrtchyan/aca
        tags: latest, ${{ github.run_number }}
     