name: Docker Image CI

on:
  push:
    branches: [ "dev", "master" ]
    paths: [ "srcs" ]
  pull_request:
    branches: [ "dev", "master" ]
    paths: [ "srcs" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Build the Docker image
    #   working-directory: ./srcs
    #   run: |
    #     docker-compose build
    #     docker-compose up --tag my-image-name:$(date +%s)       
    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./srcs
        push: true
        tags: tmkrtchyan/app:latest
    - name: apply changes to deployments
      run: |
        kubectl apply -f 05-django-app-nlb-deployment-YAML/
